name: Frontend Direct Deploy

on:
  push:
    branches: [ "dev" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 코드 체크아웃
      uses: actions/checkout@v4

    - name: Node.js 세팅
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: 의존성 설치 및 빌드
      run: |
        npm install
        npm run build

    - name: EC2로 파일 전송 (SCP)
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USERNAME }}
        key: ${{ secrets.AWS_KEY }}
        
        source: "dist/*,Dockerfile,nginx.conf"
        target: "/home/ubuntu/frontend"
        strip_components: 0 

    - name: EC2에서 Docker 빌드 및 실행 (SSH)
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USERNAME }}
        key: ${{ secrets.AWS_KEY }}
        script: |
          cd /home/ubuntu/frontend

          sudo docker stop santa-frontend || true
          sudo docker rm santa-frontend || true

          sudo docker rmi santa-frontend-img || true
          sudo docker build -t santa-frontend-img .

          sudo docker run -d --name santa-frontend \
            --network host \
            santa-frontend-img

          sudo docker image prune -f
